#!/usr/bin/env bash
#
# squat-crates-io-resume.sh — Resume crates.io publish after rate limit.
#
# crates.io rate limit for NEW crates is strict: burst 5 then 1 per 10 min.
# This script publishes the 21 remaining names with 11-min sleep between
# each (safety margin vs the 10-min limit).
#
# Total runtime: ~3h50min for 21 publishes.
#
# Usage:
#   bash scripts/squat-crates-io-resume.sh
#
# Reuses /tmp/squat-* directories generated by squat-crates-io.sh.
# Token is prompted via stdin (invisible, never argv).
#
# Tip: launch in tmux/screen so it survives terminal disconnect:
#   tmux new -s squat
#   bash scripts/squat-crates-io-resume.sh
#   (Ctrl+B then D to detach, tmux attach -t squat to resume)

set -euo pipefail

# 21 remaining names (5 already published: gradatum, gradatum-acl-auth,
# gradatum-acl-policy, gradatum-admin, gradatum-auth)
REMAINING=(
    "gradatum-cache"
    "gradatum-chat"
    "gradatum-cli"
    "gradatum-core"
    "gradatum-curator"
    "gradatum-embed"
    "gradatum-index"
    "gradatum-markdown"
    "gradatum-mcp-stub"
    "gradatum-queue"
    "gradatum-sdk-rs"
    "gradatum-search"
    "gradatum-server"
    "gradatum-storage"
    "gradatum-vault"
    "gradatum-worker"
    "gradatum-engine"
    "gradatum-protocol"
    "gradatum-studio"
    "gradatum-mcp"
    "gradatum-distill"
)

# Sleep 660s (11 min) between each publish — safety margin vs 10-min limit
readonly RATE_LIMIT_SLEEP_S=660

# ----------------------------------------------------- preflight + token ---

command -v cargo >/dev/null 2>&1 || { echo "ERROR: cargo not found"; exit 1; }

echo "==> Resume publish — ${#REMAINING[@]} crates remaining"
echo "    Total ETA: ~$((${#REMAINING[@]} * RATE_LIMIT_SLEEP_S / 60)) min ($((${#REMAINING[@]} * RATE_LIMIT_SLEEP_S / 3600))h)"
echo

# Check /tmp/squat-* dirs exist
for name in "${REMAINING[@]}"; do
    if [[ ! -d "/tmp/squat-${name}" ]]; then
        echo "ERROR: /tmp/squat-${name} missing. Re-run squat-crates-io.sh first to regenerate."
        exit 1
    fi
done

# Accept token from env var (set in current shell to avoid re-prompt on relaunch),
# otherwise prompt via stdin (invisible).
if [[ -n "${CRATES_IO_TOKEN:-}" ]]; then
    TOKEN="$CRATES_IO_TOKEN"
    echo "==> Using \$CRATES_IO_TOKEN from environment (skip prompt)."
else
    read -rsp "Paste your crates.io API token (input hidden), then Enter: " TOKEN
    echo
fi

if [[ -z "${TOKEN:-}" ]]; then
    echo "ERROR: empty token, aborting."
    exit 1
fi

# ---------------------------------------------- isolated CARGO_HOME setup ---

ORIG_CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
ISOLATED_CARGO_HOME="$(mktemp -d -t squat-resume-cargo-XXXXXX)"
export CARGO_HOME="$ISOLATED_CARGO_HOME"

cleanup() {
    rm -rf "$ISOLATED_CARGO_HOME"
    export CARGO_HOME="$ORIG_CARGO_HOME"
    unset TOKEN
}
trap cleanup EXIT INT TERM

: > "$CARGO_HOME/config.toml"
{
    echo "[registry]"
    echo "token = \"${TOKEN}\""
} > "$CARGO_HOME/credentials.toml"
chmod 600 "$CARGO_HOME/credentials.toml"
unset TOKEN

echo "==> Isolated CARGO_HOME: $CARGO_HOME (any host registry proxy bypassed)"
echo

# ---------------------------------------------- wait for rate limit reset ---

NOW=$(date -u +%s)
RESET_TARGET=$(date -d "2026-05-03 08:42:59 UTC" +%s)
WAIT_SEC=$((RESET_TARGET - NOW + 30))  # +30s buffer

if (( WAIT_SEC > 0 )); then
    echo "==> Waiting ${WAIT_SEC}s for rate-limit reset (08:42:59 UTC + 30s buffer)..."
    sleep "$WAIT_SEC"
    echo "==> Reset window passed, starting publishes."
    echo
fi

# ----------------------------------------------------- publish sequential ---

ok=0
fail=0
fail_names=()

for i in "${!REMAINING[@]}"; do
    name="${REMAINING[$i]}"
    pos=$((i + 1))
    total=${#REMAINING[@]}
    dir="/tmp/squat-${name}"

    echo "[$(date -u +%H:%M:%S) UTC] (${pos}/${total}) Publishing ${name}..."
    if (cd "${dir}" && cargo publish --allow-dirty 2>&1 | tail -2); then
        echo "  ✅ ${name} published"
        ok=$((ok + 1))
    else
        echo "  ❌ ${name} FAILED"
        fail=$((fail + 1))
        fail_names+=("${name}")
    fi

    # Sleep before next (except after last)
    if (( pos < total )); then
        echo "  ⏸  Sleeping ${RATE_LIMIT_SLEEP_S}s before next publish..."
        sleep "$RATE_LIMIT_SLEEP_S"
        echo
    fi
done

# --------------------------------------------------------------- summary ---

echo
echo "==> Resume publish results: ${ok} OK / ${fail} FAIL out of ${#REMAINING[@]}"

if (( fail > 0 )); then
    echo
    echo "Failed names (rate limit, network, or other issue):"
    for n in "${fail_names[@]}"; do
        echo "  - ${n}"
    done
    echo
    echo "Re-run this script to retry failed names (it will skip already-published ones)."
    exit 1
fi

echo
echo "==> All ${#REMAINING[@]} remaining names published. Combined with 5 from initial run = 26 total."
echo "==> Verify on: https://crates.io/users/<your-username>"
echo "==> Cleanup placeholder dirs: rm -rf /tmp/squat-gradatum*"
