//! `gradatum-admin token issue` — issues service JWT tokens.
//!
//! ## Usage
//! ```text
//! gradatum-admin token issue \
//!     --root /var/lib/gradatum \
//!     --sub mcp-stub \
//!     --scopes vault_read,vault_search \
//!     --tenant main
//! ```
//!
//! ## Effects
//! - Loads the server's Ed25519 signing seed from `{root}/config/jwt-signing-key.secret`
//! - Signs a JWT with `TokenScope::Service` (24 h TTL by default)
//! - Prints the token to stdout only (pipe-friendly, no decoration)
//!
//! ## Key source (fixed in v1.0.0)
//!
//! This command used to sign with a PKCS#8 PEM pair (`config/jwt.private.pem`)
//! generated by `gradatum-admin init`, under `kid = "gradatum-admin-issued"`.
//! `gradatum-server` holds neither that key nor that `kid`: it signs and verifies
//! with the raw seed `config/jwt-signing-key.secret` under `kid = "gradatum-v0"`.
//! Every token this command emitted was therefore rejected with
//! `401 authentication required`.
//!
//! Both signers now go through [`gradatum_auth::key_store`]. The seed is loaded,
//! never created: it belongs to the server's lifecycle. On a root where the
//! server has never booted, this command fails with an explicit message instead
//! of minting an orphan token.
//!
//! ## Security
//! - The signing seed is never logged
//! - The token is printed without trailing CRLF (compatible with `export TOKEN=$(...)`)

use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::{Args, Subcommand};
use gradatum_auth::jwt::TokenScope;
use gradatum_auth::key_store;
use gradatum_core::paths::config_dir;

/// Sub-commands of `token`.
#[derive(Debug, Subcommand)]
pub enum TokenCmd {
    /// Issues a service JWT token.
    Issue(TokenIssueArgs),
}

/// Arguments for the `token issue` sub-command.
#[derive(Debug, Args)]
pub struct TokenIssueArgs {
    /// Gradatum root directory — the same `[storage] root` the server uses.
    ///
    /// Must contain `config/jwt-signing-key.secret`, created by `gradatum-server`
    /// at first boot.
    #[arg(long)]
    pub root: PathBuf,

    /// Token subject (e.g. `mcp-stub`, `curator-worker`, `agent-xxx`).
    #[arg(long)]
    pub sub: String,

    /// Granted scopes, comma-separated (e.g. `vault_read,vault_search`).
    #[arg(long, default_value = "vault_read")]
    pub scopes: String,

    /// Target tenant.
    #[arg(long)]
    pub tenant: String,

    /// TTL override in seconds (default: 86400 s for service tokens).
    /// When absent, the service TTL from the config is used (86400 s).
    #[arg(long)]
    pub ttl_secs: Option<u64>,
}

/// Entry point for the `token` sub-command.
pub fn run(cmd: TokenCmd) -> Result<()> {
    match cmd {
        TokenCmd::Issue(args) => run_issue(args),
    }
}

/// Issues a service JWT token and prints it to stdout.
///
/// # Errors
/// Propagates the errors of [`issue_token`].
fn run_issue(args: TokenIssueArgs) -> Result<()> {
    let token = issue_token(&args)?;

    // Stdout only — pipe-friendly, no decoration or trailing CRLF.
    println!("{token}");

    Ok(())
}

/// Signs a service JWT with the server's signing key and returns it.
///
/// Separated from `run_issue` so integration tests can assert that the emitted
/// token verifies against the service the server boots with — the invariant that
/// was broken until v1.0.0.
///
/// # Errors
/// - The signing seed is missing (the server has never booted on this root),
///   unreadable, has permissions looser than `0o600`, or is corrupted.
/// - JWT signing fails.
pub fn issue_token(args: &TokenIssueArgs) -> Result<String> {
    // SSOT: same directory helper and same key_store as `gradatum-server`.
    let key_dir = config_dir(&args.root);
    let ttl_service = args.ttl_secs.unwrap_or(86400);

    let jwt = key_store::load(
        &key_dir,
        3600, // ttl_human — unused for TokenScope::Service
        ttl_service,
    )
    .with_context(|| {
        format!(
            "loading the server signing key for root {}",
            args.root.display()
        )
    })?;

    // Parse scopes (comma-separated, whitespace trimmed).
    let scopes: Vec<String> = args
        .scopes
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();

    jwt.sign(&args.sub, &scopes, TokenScope::Service, &args.tenant)
        .map_err(|e| anyhow::anyhow!("JWT signing failed: {e}"))
}
