//! On-disk JWT signing key — single source of truth for every process.
//!
//! ## Why this module exists
//!
//! `gradatum-server` signs and verifies JWTs with a raw 32-byte Ed25519 seed
//! stored in `<key_dir>/jwt-signing-key.secret`, under `kid = "gradatum-v0"`.
//! `gradatum-admin token issue` used to sign with a *different* key — a PKCS#8
//! PEM pair generated by `gradatum-admin init` — under
//! `kid = "gradatum-admin-issued"`. The server holds neither that key nor that
//! `kid`, so every token issued through the documented operator path was
//! rejected with `401 authentication required`.
//!
//! The two signers now go through this module. The key name, the `kid` and the
//! audience live here and nowhere else: a future change cannot desynchronise
//! them again.
//!
//! ## Entry points
//!
//! | Caller | Function | Behaviour when the key is absent |
//! |---|---|---|
//! | `gradatum-server` (boot) | [`load_or_generate`] | generates and persists it |
//! | `gradatum-admin` (CLI) | [`load`] | fails — never generates |
//!
//! The asymmetry is deliberate: the server owns the key's lifecycle. If the CLI
//! could generate it, running `token issue` before the first boot would mint a
//! key the server would later refuse to adopt — reintroducing the very
//! split-brain this module removes.
//!
//! ## Security
//!
//! - The seed only ever travels through [`secrecy::ExposeSecret`].
//! - Only the file path is ever logged, never the content.
//! - Writes are atomic: chmod 600 is applied before the rename, leaving no
//!   world-readable window.
//! - Permissions looser than `0o600` are refused (fail-closed).

use std::path::{Path, PathBuf};

use gradatum_core::secrets::{FileSecretsProvider, SecretsError, SecretsProvider};
use secrecy::ExposeSecret;

use crate::jwt::JwtService;

/// Normalised name of the signing seed in [`FileSecretsProvider`].
///
/// Resolved path: `<key_dir>/jwt-signing-key.secret`.
pub const SIGNING_KEY_NAME: &str = "jwt-signing-key";

/// `kid` header carried by every token this deployment issues.
///
/// Fixed rather than derived from a filename: `JwtService::verify` rejects a
/// mismatched `kid` before any cryptographic work, so signer and verifier must
/// agree on a stable literal.
pub const SIGNING_KID: &str = "gradatum-v0";

/// Audience of the issued tokens (exact match enforced at verification).
/// JWT issuer — identifies the service that minted the token.
pub const ISSUER: &str = "gradatum";
/// JWT audience — target service name.
pub const AUDIENCE: &str = "gradatum";

/// Failures of the on-disk signing key store.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum KeyStoreError {
    /// No signing key at the expected path, and this entry point does not create one.
    #[error(
        "JWT signing key not found at {path} — it is created by gradatum-server at first boot; \
         start the server once, then retry"
    )]
    NotFound {
        /// Expected path of the seed file.
        path: PathBuf,
    },

    /// The seed could not be read (I/O, or permissions looser than `0o600`).
    #[error("reading the JWT signing key at {path}")]
    Read {
        /// Path of the seed file.
        path: PathBuf,
        /// Underlying secrets-provider error.
        #[source]
        source: SecretsError,
    },

    /// The seed could not be persisted at first boot.
    #[error("writing the JWT signing key to {path}")]
    Write {
        /// Path of the seed file.
        path: PathBuf,
        /// Underlying secrets-provider error.
        #[source]
        source: SecretsError,
    },

    /// The stored seed is not a valid Ed25519 seed (truncated or corrupted file).
    #[error("invalid JWT signing key at {path}: {reason}")]
    Invalid {
        /// Path of the seed file.
        path: PathBuf,
        /// Why the seed was rejected (e.g. wrong length).
        reason: &'static str,
    },
}

/// Path of the seed file inside `key_dir`.
#[must_use]
pub fn signing_key_path(key_dir: &Path) -> PathBuf {
    key_dir.join(format!("{SIGNING_KEY_NAME}.secret"))
}

/// Builds a [`JwtService`] from an existing seed — never creates one.
///
/// Intended for every process that is *not* the server: it must adopt the
/// server's key, never mint its own.
///
/// # Errors
///
/// - [`KeyStoreError::NotFound`] when the seed file does not exist.
/// - [`KeyStoreError::Read`] on I/O failure or permissions looser than `0o600`.
/// - [`KeyStoreError::Invalid`] when the stored seed is not 32 bytes.
#[must_use = "the returned JwtService is the only way to sign or verify tokens"]
pub fn load(
    key_dir: &Path,
    ttl_human_secs: u64,
    ttl_service_secs: u64,
) -> Result<JwtService, KeyStoreError> {
    let provider = FileSecretsProvider::new(key_dir);
    let secret = match provider.get(SIGNING_KEY_NAME) {
        Ok(s) => s,
        Err(SecretsError::NotFound { .. }) => {
            return Err(KeyStoreError::NotFound {
                path: signing_key_path(key_dir),
            });
        }
        Err(source) => {
            return Err(KeyStoreError::Read {
                path: signing_key_path(key_dir),
                source,
            });
        }
    };

    build_service(
        key_dir,
        secret.expose_secret(),
        ttl_human_secs,
        ttl_service_secs,
    )
}

/// Builds a [`JwtService`], generating and persisting the seed if it is absent.
///
/// Reserved for `gradatum-server`, which owns the key's lifecycle.
///
/// | File state | Outcome |
/// |---|---|
/// | Present, perms ≤ `0o600` | loaded |
/// | Absent | generated, persisted atomically (chmod 600), `WARN` emitted |
/// | Present, perms > `0o600` | [`KeyStoreError::Read`] |
/// | Present, ≠ 32 bytes | [`KeyStoreError::Invalid`] |
///
/// # Errors
///
/// - [`KeyStoreError::Read`] on I/O failure or overly permissive file mode.
/// - [`KeyStoreError::Write`] when the freshly generated seed cannot be persisted.
/// - [`KeyStoreError::Invalid`] when the stored seed is not 32 bytes.
#[must_use = "the returned JwtService is the only way to sign or verify tokens"]
pub fn load_or_generate(
    key_dir: &Path,
    ttl_human_secs: u64,
    ttl_service_secs: u64,
) -> Result<JwtService, KeyStoreError> {
    let provider = FileSecretsProvider::new(key_dir);
    let path = signing_key_path(key_dir);

    let secret = match provider.get(SIGNING_KEY_NAME) {
        Ok(s) => {
            tracing::info!(path = %path.display(), "JWT key loaded from persistent file");
            s
        }
        Err(SecretsError::NotFound { .. }) => {
            // `seed` is Zeroizing<[u8;32]>: wiped from memory at end of scope.
            let (seed, _signing_key) = JwtService::generate_signing_bytes();
            provider
                .write_atomic(SIGNING_KEY_NAME, seed.as_ref())
                .map_err(|source| KeyStoreError::Write {
                    path: path.clone(),
                    source,
                })?;

            tracing::warn!(
                path = %path.display(),
                "JWT key generated and persisted — \
                 ALL EXISTING JWTs ARE INVALIDATED; API keys are unaffected \
                 (first startup or manual rotation of the .secret file)"
            );

            // Re-read through the provider to reuse the canonical path handling.
            // The key was just written, so NotFound is not reachable here.
            provider
                .get(SIGNING_KEY_NAME)
                .map_err(|source| KeyStoreError::Read {
                    path: path.clone(),
                    source,
                })?
        }
        Err(source) => return Err(KeyStoreError::Read { path, source }),
    };

    build_service(
        key_dir,
        secret.expose_secret(),
        ttl_human_secs,
        ttl_service_secs,
    )
}

/// Turns raw seed bytes into a [`JwtService`] bound to the deployment `kid` and audience.
///
/// The seed is never logged — only the path is, and only by the callers.
fn build_service(
    key_dir: &Path,
    bytes: &[u8],
    ttl_human_secs: u64,
    ttl_service_secs: u64,
) -> Result<JwtService, KeyStoreError> {
    JwtService::from_signing_bytes(
        bytes,
        SIGNING_KID.to_string(),
        ISSUER.to_string(),
        AUDIENCE.to_string(),
        ttl_human_secs,
        ttl_service_secs,
    )
    .map_err(|reason| KeyStoreError::Invalid {
        path: signing_key_path(key_dir),
        reason,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::jwt::TokenScope;
    use std::os::unix::fs::PermissionsExt;
    use tempfile::TempDir;

    const TTL_HUMAN: u64 = 3600;
    const TTL_SERVICE: u64 = 86400;

    /// **The P0 regression test.**
    ///
    /// A token issued by the CLI path ([`load`]) must verify against the service
    /// the server booted with ([`load_or_generate`]). Before the fix the CLI
    /// signed with a PKCS#8 PEM pair under `kid = "gradatum-admin-issued"` while
    /// the server verified a raw seed under `kid = "gradatum-v0"`, so this
    /// round-trip returned `InvalidKid` — the `401` observed in production.
    #[test]
    fn token_issued_by_cli_path_verifies_against_server_service() {
        let dir = TempDir::new().expect("tempdir");

        // Server boot: creates the key.
        let server = load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE)
            .expect("first boot must generate the key");

        // Operator CLI: adopts the same key, does not create one.
        let cli = load(dir.path(), TTL_HUMAN, TTL_SERVICE)
            .expect("the CLI must load the key created by the server");

        let token = cli
            .sign(
                "diag",
                &["vault_read".to_string()],
                TokenScope::Service,
                "main",
            )
            .expect("signing must succeed");

        let claims = server
            .verify(&token)
            .expect("the server must accept a token issued by the CLI path");

        assert_eq!(claims.sub, "diag");
        assert_eq!(claims.tenant_id, "main");
    }

    /// Both entry points agree on the `kid`, which `verify` checks before any crypto.
    #[test]
    fn both_entry_points_use_the_same_kid() {
        let dir = TempDir::new().expect("tempdir");
        let server = load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE).expect("generate");
        let cli = load(dir.path(), TTL_HUMAN, TTL_SERVICE).expect("load");

        assert_eq!(server.kid(), SIGNING_KID);
        assert_eq!(cli.kid(), SIGNING_KID);
    }

    /// Extracts the error, without requiring `Debug` on `JwtService`.
    ///
    /// `JwtService` deliberately does not implement `Debug` — it holds the
    /// signing key — so `Result::expect_err` is unusable here.
    fn expect_err(result: Result<JwtService, KeyStoreError>, msg: &str) -> KeyStoreError {
        match result {
            Err(e) => e,
            Ok(_) => panic!("{msg}"),
        }
    }

    /// `load` must never create a key: a CLI-minted key would be orphaned.
    #[test]
    fn load_refuses_to_create_a_missing_key() {
        let dir = TempDir::new().expect("tempdir");

        let err = expect_err(
            load(dir.path(), TTL_HUMAN, TTL_SERVICE),
            "load must fail when no key exists",
        );

        assert!(
            matches!(err, KeyStoreError::NotFound { .. }),
            "expected NotFound, got: {err:?}"
        );
        assert!(
            !signing_key_path(dir.path()).exists(),
            "load must not have created the key file"
        );
    }

    /// First boot writes the seed with mode exactly `0o600`.
    #[test]
    fn first_boot_generates_the_file_chmod_600() {
        let dir = TempDir::new().expect("tempdir");

        let jwt = load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE).expect("generate");

        let key_path = signing_key_path(dir.path());
        assert!(
            key_path.exists(),
            "the key file must be created on first boot"
        );

        let mode = std::fs::metadata(&key_path)
            .expect("metadata")
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o600, "expected 0o600, got 0o{mode:04o}");

        let token = jwt
            .sign("sub-test", &["read".to_string()], TokenScope::Human, "main")
            .expect("signing must succeed");
        assert!(!token.is_empty());
    }

    /// A token survives a restart: the second boot loads the persisted seed.
    #[test]
    fn second_boot_loads_the_same_key() {
        let dir = TempDir::new().expect("tempdir");

        let boot_1 = load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE).expect("first boot");
        let token = boot_1
            .sign(
                "user-persistance",
                &["read".to_string()],
                TokenScope::Human,
                "main",
            )
            .expect("signing at boot 1");

        let boot_2 = load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE).expect("second boot");
        let claims = boot_2
            .verify(&token)
            .expect("the token must survive a restart");

        assert_eq!(claims.sub, "user-persistance");
    }

    /// Permissions looser than `0o600` are refused rather than silently accepted.
    #[test]
    fn too_open_permissions_are_refused() {
        let dir = TempDir::new().expect("tempdir");
        let key_path = signing_key_path(dir.path());

        std::fs::write(&key_path, vec![0u8; 32]).expect("write");
        std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o644))
            .expect("chmod 644");

        let err = expect_err(
            load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE),
            "overly open permissions must be refused",
        );

        assert!(
            matches!(err, KeyStoreError::Read { .. }),
            "expected Read, got: {err:?}"
        );
    }

    /// A truncated seed makes the server refuse to boot instead of using a bad key.
    #[test]
    fn corrupted_seed_is_rejected() {
        let dir = TempDir::new().expect("tempdir");
        let key_path = signing_key_path(dir.path());

        std::fs::write(&key_path, vec![0xABu8; 31]).expect("write corrupted seed");
        std::fs::set_permissions(dir.path(), std::fs::Permissions::from_mode(0o700))
            .expect("chmod 700 dir");
        std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o600))
            .expect("chmod 600 file");

        let err = expect_err(
            load_or_generate(dir.path(), TTL_HUMAN, TTL_SERVICE),
            "a 31-byte seed must be rejected",
        );

        assert!(
            matches!(err, KeyStoreError::Invalid { .. }),
            "expected Invalid, got: {err:?}"
        );
    }
}
